//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.Bll.Context {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS.Bll.Context.AppText", typeof(AppText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จัดการสิทธิ์การใช้งานระบบ.
        /// </summary>
        public static string MenuAppCompositeRole {
            get {
                return ResourceManager.GetString("MenuAppCompositeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสิทธิ์ผู้ใช้งาน.
        /// </summary>
        public static string MenuAssignUserRole {
            get {
                return ResourceManager.GetString("MenuAssignUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดสิทธิ์การใช้งาน.
        /// </summary>
        public static string MenuAuthorization {
            get {
                return ResourceManager.GetString("MenuAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คณะกรรมการบริษัท.
        /// </summary>
        public static string MenuBoardUser {
            get {
                return ResourceManager.GetString("MenuBoardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบปะหน้าสรุปการจ่ายเงิน ประเภท BAHTNET.
        /// </summary>
        public static string MenuBSBNT {
            get {
                return ResourceManager.GetString("MenuBSBNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตั้งค่า.
        /// </summary>
        public static string MenuBSCFGroup {
            get {
                return ResourceManager.GetString("MenuBSCFGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบนำส่งเอกสารสรุปการจ่ายเงิน ประเภท Direct Credit.
        /// </summary>
        public static string MenuBSDCP {
            get {
                return ResourceManager.GetString("MenuBSDCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบนำส่งเอกสารธนาคาร.
        /// </summary>
        public static string MenuBSGroup {
            get {
                return ResourceManager.GetString("MenuBSGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบนำส่งเอกสารสรุปการจ่ายเงิน ประเภท Business Net.
        /// </summary>
        public static string MenuBSMCL {
            get {
                return ResourceManager.GetString("MenuBSMCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบนำส่งเอกสารสรุปการจ่ายเงิน ประเภท Cheque Issue.
        /// </summary>
        public static string MenuBSMCP {
            get {
                return ResourceManager.GetString("MenuBSMCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการ.
        /// </summary>
        public static string MenuBSMGTGroup {
            get {
                return ResourceManager.GetString("MenuBSMGTGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ลงนาม.
        /// </summary>
        public static string MenuBSSigner {
            get {
                return ResourceManager.GetString("MenuBSSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบนำส่งเอกสารสรุปการจ่ายเงิน ประเภท Express Cheque.
        /// </summary>
        public static string MenuBSXMQ {
            get {
                return ResourceManager.GetString("MenuBSXMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบขออนุมัติเบิกเงิน.
        /// </summary>
        public static string MenuCA {
            get {
                return ResourceManager.GetString("MenuCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงานเบิกเงินทดรองจ่ายคงค้างเกิน 45 วัน.
        /// </summary>
        public static string MenuCADelay {
            get {
                return ResourceManager.GetString("MenuCADelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติดตามการเบิกเงินทดรองจ่าย.
        /// </summary>
        public static string MenuCAFollowReceive {
            get {
                return ResourceManager.GetString("MenuCAFollowReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบเบิกเงินทดรองจ่าย.
        /// </summary>
        public static string MenuCAGroup {
            get {
                return ResourceManager.GetString("MenuCAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการ.
        /// </summary>
        public static string MenuCAMGTGroup {
            get {
                return ResourceManager.GetString("MenuCAMGTGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตารางสรุปการขอเบิกเงิน(การเงิน).
        /// </summary>
        public static string MenuCAPlanning {
            get {
                return ResourceManager.GetString("MenuCAPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบิกเงินทดรองจ่าย.
        /// </summary>
        public static string MenuCAReceive {
            get {
                return ResourceManager.GetString("MenuCAReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงาน.
        /// </summary>
        public static string MenuCARPGroup {
            get {
                return ResourceManager.GetString("MenuCARPGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลส่วนกลาง.
        /// </summary>
        public static string MenuCentralSetting {
            get {
                return ResourceManager.GetString("MenuCentralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าการทำงาน.
        /// </summary>
        public static string MenuConfigureValue {
            get {
                return ResourceManager.GetString("MenuConfigureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้บริหารระดับสูง.
        /// </summary>
        public static string MenuExecutiveUser {
            get {
                return ResourceManager.GetString("MenuExecutiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปฏิทินวันหยุด.
        /// </summary>
        public static string MenuHolidayCalendar {
            get {
                return ResourceManager.GetString("MenuHolidayCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string MenuInbox {
            get {
                return ResourceManager.GetString("MenuInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบขออนุมัติใบสำคัญจ่ายเงินสด (Cash).
        /// </summary>
        public static string MenuPVCash {
            get {
                return ResourceManager.GetString("MenuPVCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string MenuPVCCTR {
            get {
                return ResourceManager.GetString("MenuPVCCTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการผู้รับรองพิเศษ.
        /// </summary>
        public static string MenuPVCFGroup {
            get {
                return ResourceManager.GetString("MenuPVCFGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบขออนุมัติใบสำคัญขอจ่ายเช็ค (Cheque).
        /// </summary>
        public static string MenuPVCheque {
            get {
                return ResourceManager.GetString("MenuPVCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบนำส่งเอกสารใบสำคัญ.
        /// </summary>
        public static string MenuPVG {
            get {
                return ResourceManager.GetString("MenuPVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบสำคัญขอจ่าย / จ่าย.
        /// </summary>
        public static string MenuPVGroup {
            get {
                return ResourceManager.GetString("MenuPVGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการ.
        /// </summary>
        public static string MenuPVMGTGroup {
            get {
                return ResourceManager.GetString("MenuPVMGTGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ตรวจสอบก่อนผู้อนุมัติ.
        /// </summary>
        public static string MenuPVRV {
            get {
                return ResourceManager.GetString("MenuPVRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มความรับผิดชอบ.
        /// </summary>
        public static string MenuRespGroup {
            get {
                return ResourceManager.GetString("MenuRespGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลทั่วไป.
        /// </summary>
        public static string MenuValueHelpSetting {
            get {
                return ResourceManager.GetString("MenuValueHelpSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิ์อำนาจการอนุมัติ.
        /// </summary>
        public static string MenuWorkflowAuthority {
            get {
                return ResourceManager.GetString("MenuWorkflowAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดกรอกข้อมูล.
        /// </summary>
        public static string PleaseFill {
            get {
                return ResourceManager.GetString("PleaseFill", resourceCulture);
            }
        }
    }
}
